// Torznab category constants
// Reference: https://wiki.servarr.com/prowlarr/cardinality

const CATEGORIES = {
  MOVIES: 2000,
  MOVIES_FOREIGN: 2010,
  MOVIES_OTHER: 2020,
  MOVIES_SD: 2030,
  MOVIES_HD: 2040,
  MOVIES_UHD: 2045,
  MOVIES_BLURAY: 2050,
  MOVIES_3D: 2060,
  TV: 5000,
  TV_WEBDL: 5010,
  TV_FOREIGN: 5020,
  TV_SD: 5030,
  TV_HD: 5040,
  TV_UHD: 5045,
  TV_SPORT: 5060,
  TV_ANIME: 5070,
  TV_DOCUMENTARY: 5080
}

// Grouped category strings for Torznab search queries
const MOVIE_CATS = [
  CATEGORIES.MOVIES, CATEGORIES.MOVIES_FOREIGN, CATEGORIES.MOVIES_SD,
  CATEGORIES.MOVIES_HD, CATEGORIES.MOVIES_UHD, CATEGORIES.MOVIES_BLURAY,
  CATEGORIES.MOVIES_3D
].join(',')

const TV_CATS = [
  CATEGORIES.TV, CATEGORIES.TV_WEBDL, CATEGORIES.TV_FOREIGN,
  CATEGORIES.TV_SD, CATEGORIES.TV_HD, CATEGORIES.TV_UHD,
  CATEGORIES.TV_ANIME, CATEGORIES.TV_DOCUMENTARY
].join(',')

const SPORT_CATS = String(CATEGORIES.TV_SPORT)

module.exports = { CATEGORIES, MOVIE_CATS, TV_CATS, SPORT_CATS }
